// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfknV8wY5n6vv-0CudGGBZCb_Q1YR7qGA',
    appId: '1:994119903709:web:2bb2e85ae276344f0a2e34',
    messagingSenderId: '994119903709',
    projectId: 'open-chat-app-e8420',
    authDomain: 'open-chat-app-e8420.firebaseapp.com',
    storageBucket: 'open-chat-app-e8420.appspot.com',
    measurementId: 'G-ENTN1SL3GE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpFo8FEL4ByqLw-iaTl9LK5UphUjcQczE',
    appId: '1:994119903709:android:82ac9937741035260a2e34',
    messagingSenderId: '994119903709',
    projectId: 'open-chat-app-e8420',
    storageBucket: 'open-chat-app-e8420.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuAjvnSEvTNNg4ikR6RP_5VYLwPcuvsRw',
    appId: '1:994119903709:ios:4e71fd4b244bd8550a2e34',
    messagingSenderId: '994119903709',
    projectId: 'open-chat-app-e8420',
    storageBucket: 'open-chat-app-e8420.appspot.com',
    iosBundleId: 'com.example.openChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuAjvnSEvTNNg4ikR6RP_5VYLwPcuvsRw',
    appId: '1:994119903709:ios:4e71fd4b244bd8550a2e34',
    messagingSenderId: '994119903709',
    projectId: 'open-chat-app-e8420',
    storageBucket: 'open-chat-app-e8420.appspot.com',
    iosBundleId: 'com.example.openChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfknV8wY5n6vv-0CudGGBZCb_Q1YR7qGA',
    appId: '1:994119903709:web:60bf3db32bf5e3d00a2e34',
    messagingSenderId: '994119903709',
    projectId: 'open-chat-app-e8420',
    authDomain: 'open-chat-app-e8420.firebaseapp.com',
    storageBucket: 'open-chat-app-e8420.appspot.com',
    measurementId: 'G-S4DJB8500J',
  );
}
